//! # ce-sched-core — the pure placement brain + shared daemon-API wire types.
//!
//! Smart, latency- and benchmark-aware, BFT-safe job placement on the CE fabric, as a **pure**
//! library: every type and function here is a deterministic function of its arguments — no node, no
//! network, no I/O. The daemon ([`ce-sched-daemon`]) and the SDKs ([`ce-sched-sdk`], `sdk-ts`) are
//! thin shells over this core (see `../ce-bench/docs/RUST-DAEMON-ARCH.md`).
//!
//! This is the Rust port of the JS `src/` modules (kept in place during the rewrite):
//!
//! | Rust module     | JS source        | Role |
//! |-----------------|------------------|------|
//! | [`api`]         | `src/types.js`   | shared wire types: [`api::JobSpec`], [`api::PlacementPlan`], [`api::FabricMap`] |
//! | [`graph`]       | `src/graph.js`   | latency queries (embedding, regions, shortest path) over the map |
//! | [`scorer`]      | `src/scorer.js`  | per-candidate `[0,1]` static scoring (latency/benchFit/trust/price) |
//! | [`vendor`]      | `src/vendor.js`  | diversity / risk: grouping keys, caps, penalty |
//! | [`placer`]      | `src/placer.js`  | the selector: `(JobSpec, FabricMap) -> PlacementPlan` |
//!
//! The placement entry point is [`placer::plan`]; everything else is the substrate it composes.
//! Determinism is part of the contract: the beacon-seeded PRNG ([`graph::Mulberry32`]) and the seed
//! mix ([`placer::beacon_seed`]) reproduce the JS engine bit-for-bit, so a plan is replayable across
//! both implementations from `(beacon, request, map)`.
//!
//! ## Test coverage
//! Because the core is pure it is exhaustively unit-testable with fixtures and **no live node** — the
//! tests live in `#[cfg(test)]` modules at the bottom of each module. The JS `__selftest` fixtures
//! are translated per module, and the placer's selection tests are pinned to reference outputs
//! generated by running the JS engine on the identical fixtures/seeds.

pub mod api;
pub mod graph;
pub mod placer;
pub mod scorer;
pub mod vendor;

// Re-export the most-used wire types at the crate root so callers write `ce_sched_core::JobSpec`.
pub use api::{
    BeaconRef, ByKind, Cohort, CpuProfile, Demand, DemandAxis, DeploySpec, DispatchResult,
    Dispatched, FabricMap, FabricNode, FabricStats, GpuInfo, Groups, JobSpec, LlmInfo, MemoryInfo,
    MeshEdge, MeshSummary, NodeCapacity, NodeHistory, NodeId, NodeProfile, Objective, PlaceRequest,
    PlacementPlan, PlanTarget, Redundancy, RedundancyPolicy, RejectedHost, RuntimeInfo, Selection,
    StorageInfo, Weights, OBJECTIVE_WEIGHTS,
};
pub use graph::{build_graph, Graph, GraphOptions, LatencyView};
pub use placer::{beacon_seed, feasible, plan, redundancy_for, select, Candidate, PlanError};
pub use scorer::{clamp01, resolve_weights, static_score, StaticScore};
pub use vendor::{per_group_cap, tag_candidates};
